# Generated by Django 6.0.2 on 2026-02-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("instructions", models.TextField()),
                (
                    "flavor_profile",
                    models.CharField(
                        choices=[
                            ("spicy", "🌶️ Spicy"),
                            ("sweet", "🍩 Sweet"),
                            ("savory", "🥩 Savory"),
                            ("sour", "🍋 Sour"),
                            ("umami", "🍄 Umami"),
                        ],
                        default="savory",
                        max_length=20,
                    ),
                ),
                ("ingredients", models.ManyToManyField(to="recipes.ingredient")),
            ],
        ),
    ]
