# Generated by Django 6.0.2 on 2026-02-10 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="recipe", name="ingredients",),
        migrations.AddField(
            model_name="recipe",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="flavor_profile",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="review",
            name="cooked_status",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(name="Ingredient",),
    ]
