# Generated by Django 6.0.2 on 2026-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_recipe_ingredients_recipe_favorites_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="flavor_profile",
            field=models.CharField(
                choices=[
                    ("spicy", "🌶️ Spicy"),
                    ("sweet", "🍩 Sweet"),
                    ("savory", "🥩 Savory"),
                    ("sour", "🍋 Sour"),
                    ("umami", "🍄 Umami"),
                ],
                default="savory",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="cooked_status",
            field=models.BooleanField(default=False, verbose_name="I cooked 👨\u200d🍳"),
        ),
    ]
