# Generated by Django 6.0.2 on 2026-02-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_flavor_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="cooked_status",
            field=models.BooleanField(
                default=False, verbose_name="I made this! 👨\u200d🍳"
            ),
        ),
    ]
